module.exports = {
  ADD_SUBMODULE: 'ADD_SUBMODULE',
  ADD_TREE_NODE: 'ADD_TREE_NODE',
  APPEND_HISTORY: 'APPEND_HISTORY',
  DELETE_TREE_NODE: 'DELETE_TREE_NODE',
  FETCH_CONFIG: 'FETCH_CONFIG',
  FORWARD_HISTORY: 'FORWARD_HISTORY',
  MAKE_SUBMODULE: 'MAKE_SUBMODULE',
  REPLACE_SUBMODULE: 'REPLACE_SUBMODULE',
  REPLACE_TREE_NODE: 'REPLACE_TREE_NODE',
  REWIND_HISTORY: 'REWIND_HISTORY',
  SET_EDITOR_PATH: 'SET_EDITOR_PATH',
  STORE_CONFIG_KEYS: 'STORE_CONFIG_KEYS',
  TOGGLE_PREVIEW: 'TOGGLE_PREVIEW',
};

